### PR TITLE
Removal of references to the Dashboard Project Type

### LINKED ISSUE #4114: Dashboard Functionality Removed - API's Not Updated
## Description of bug
When DNN Platform was migrated to using the Persona Bar, starting with version 9.0.0, the older Dashboard extension point was not brought forward.  

However, all of the dashboard API's, methods, and implementation remain part of the DNN API and could be used by developers with no real results 

## Steps to reproduce
Create a new Dashboard Extension and notice that it is not displayed anywhere.

## Current behavior
Developers can build a Dashboard Extension without any warnings, and the functionality will not work.

## Expected behavior
Developers should get a build warning and notice that the API's will be removed.

## Discussion Point
Traditionally, these API's would be something that should be flagged for removal in version 11.0.0 given the current version.  However, since this functionality is not working now, I would propose that we flag for removal in 10.0.0 to coincide with all other breaking changes already planned.  

## Affected version

* [x] 09.07.01 latest supported release

### PR DESCRIPTION
**Pull request by mitchelsellers**
Fixes #4114 

Upon further review, since version 8.0.0 it has been impossible to install, or uninstall Dashboard components.  However, there were lingering references.  Given this, I have opted in this PR to remove the references rather than simply flagging as there wasn't anything easily flaggable.  I can adjust if needed.

### CODE REVIEW

File: Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Constants.cs [hunk 1]
```diff
@@ -2,58 +2,57 @@
...
-    {
-        internal const string DefaultExtensionImage = "icon_extensions_32px.png";
-        internal const string DefaultLanguageImage = "icon_languagePack.gif";
-        internal const string DefaultAuthenicationImage = "icon_authentication.png";
-        internal const string DefaultContainerImage = "icon_container.gif";
-        internal const string DefaultSkinImage = "icon_skin.gif";
-        internal const string DefaultProviderImage = "icon_provider.gif";
-        internal const string DefaultLibraryImage = "icon_library.png";
-        internal const string DefaultWidgetImage = "icon_widget.png";
-        internal const string DefaultDashboardImage = "icon_dashboard.png";
```
Comment (bdukes) [inline Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Constants.cs:54]: Do we want to delete this image also?  Or leave it since someone might be using it for something else?

File: DNN Platform/Library/Services/Installer/Util.cs [hunk 2]
```diff
@@ -616,12 +616,6 @@ private static string ValidateNode(string propValue, bool isRequired, Logger log
         public static string CONFIG_Committed = GetLocalizedString("CONFIG_Committed");
         public static string CONFIG_RolledBack = GetLocalizedString("CONFIG_RolledBack");
         public static string CONFIG_Updated = GetLocalizedString("CONFIG_Updated");
-        public static string DASHBOARD_ReadSuccess = GetLocalizedString("DASHBOARD_ReadSuccess");
```
Comment (bdukes) [inline DNN Platform/Library/Services/Installer/Util.cs:619]: Let's also remove the resources from the resx file: https://github.com/dnnsoftware/Dnn.Platform/blob/f5240f8148ad6bdae497fcba1964f49fd98cd756/DNN%20Platform/Website/App_GlobalResources/SharedResources.resx#L1407-L1424

Comment (bdukes) [reply DNN Platform/Library/Services/Installer/Util.cs:619]: And this one: https://github.com/dnnsoftware/Dnn.Platform/blob/80e48fcde4694d70960253d401a8fcd6851608eb/Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Extensions/App_LocalResources/Extensions.resx#L252-L254

File: Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Constants.cs (hunk 1 above)
Comment (mitchelsellers) [reply Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Constants.cs:54]: I think we have to leave  the image due to others possibly using it

File: DNN Platform/Library/Services/Installer/Util.cs (hunk 2 above)
Comment (mitchelsellers) [reply DNN Platform/Library/Services/Installer/Util.cs:619]: Just pushed a commit for this one

**Review by bdukes — APPROVED** [review]

**Review by donker — APPROVED** [review]
