### PR TITLE
module friendly name updated as part of module extension update

### LINKED ISSUE #4081: Changing Module Friendly Name in package extention doesn't reflect new name in Add Module dialog
## Description of bug
Changing Module Friendly Name through the "Extension" menu change it in Packages table but it doesn't reflect new name in Add Module menu when adding that module in page.

## Steps to reproduce
1. Go to Persona Bar > Settings > Extensions
2. Scroll to "Html" module and click "Edit" (pencil) icon 
3. Modify the Friendly Name and click "Save"
4. Create/edit a page
5. Click "Add Module" in edit bar at the bottom
6. "Add Module" dialog opens

## Current behavior
"Html" module still shows old friendly name. 

## Expected behavior
"Html" module should show modified friendly name

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [x] 10.00.00 alpha build
* [x] 09.07.02 release candidate
* [x] 09.07.01 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

### PR DESCRIPTION
**Pull request by tauqeer-haider**
Fixes #4081 

## Summary

Changing friendly name for a module in extensions page updates it only in Packages table and doesn't update it in DesktopModules table. Included friendly name property to be updated in DesktopModules table.

### CODE REVIEW

File: Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Editors/ModulePackageEditor.cs [hunk 1]
```diff
@@ -64,56 +64,9 @@ public bool SavePackageSettings(PackageSettingsDto packageSettings, out string e
...
-                                var moduleControl = JsonConvert.DeserializeObject<ModuleControlDto>(settingValue);
-                                SaveModuleControl(moduleControl);
-                                break;
-                            case "deletemodulecontrol":
-                                DeleteModuleControl(Convert.ToInt32(settingValue));
-                                break;
-                        }
-                    }
+                {
+                    this.UpdateModuleProperties(desktopModule, packageSettings.Settings);
```
Comment (mitchelsellers) [inline Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Editors/ModulePackageEditor.cs:68]: Unless I'm missing something here in the process, why are we looping twice now through properties with settings and editoractions.  As settings was not used before?

**Review by mitchelsellers — CHANGES_REQUESTED** [review]

File: Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Editors/ModulePackageEditor.cs (hunk 1 above)
Comment (tauqeer-haider) [reply Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Editors/ModulePackageEditor.cs:68]: It was updating editoractions only for modules before this change.

File: Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Editors/ModulePackageEditor.cs [hunk 2]
```diff
@@ -125,8 +78,64 @@ public bool SavePackageSettings(PackageSettingsDto packageSettings, out string e
...
-
+        }
+
+        private void UpdateModuleProperties(DesktopModuleInfo desktopModule, IDictionary<string, string> settings)
+        {
+            foreach (var settingName in settings.Keys)
+            {
+                var settingValue = settings[settingName];
+
+                switch (settingName.ToLowerInvariant())
```
Comment (Yabgu) [inline Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Editors/ModulePackageEditor.cs:89]: Redundant dictionary search can be eliminated:

```CS
foreach (var setting in settings.Keys)
{
    var settingName = setting.Key;
    var settingValue = setting.Value;
    ...
```

**Review by bdukes — APPROVED** [review]

File: Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Editors/ModulePackageEditor.cs (hunk 1 above)
Comment (bdukes) [reply Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Editors/ModulePackageEditor.cs:68]: @mitchelsellers I think this looks right, there are two collections from the client which need contain actions/settings to process on the server.

**Review by mitchelsellers — APPROVED** [review]
