### PR TITLE
Issue-4066 - Create multiple pages validation passed with same page name on same hierarchy

### LINKED ISSUE #4066: Create multiple pages validation passed with same page name on same hierarchy
## Description of bug
Validation doesn't show error messages when the same page with the same hierarchy is tried to be added.

## Steps to reproduce
1. Login as host user
2. Go to Persona Bar -> Content -> Pages
3. Click "Add Multiple Pages"
4. Enter page name :
```
Test
Test
>Test1
>Test2
>Test1
>Test1
>>Test2
>>Test
>>>Test
>>>Test4
>>Test2
>>Test3
>Test3
>>Test3
>>>Test4
Test1
Test3
```
5. Click "Validate Page(s)"

## Current behavior
"17 pages were validated."  message shown

## Expected behavior
The following should be shown:
17 pages were validated.

Test: The Page Name you chose is already being used for another page at the same level of the page hierarchy.
,Test1: The Page Name you chose is already being used for another page at the same level of the page hierarchy.
,Test1: The Page Name you chose is already being used for another page at the same level of the page hierarchy.
,Test2: The Page Name you chose is already being used for another page at the same level of the page hierarchy.

## Screenshots
Reproduction Video: https://drive.google.com/open?id=1znAyARHN_uP3cJ_q59_F5lzi9sSqDW69

## Affected version

* [x] 10.00.00 alpha build
* [ ] 09.07.01 release candidate
* [ ] 09.07.00 latest supported release

## Affected browser

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

### PR DESCRIPTION
**Pull request by berkarslan-xo**
Fixes #4066 

## Summary

Duplicate check is added for multi-page addition. The validation considers the same-named pages in different hierarchies as well.

Demo: https://drive.google.com/file/d/1lWurDaDGXlM6XBYRwQqWb_plMmnhXiIx/view?usp=sharing

### CODE REVIEW

File: Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/BulkPagesController.cs [hunk 1]
```diff
@@ -111,6 +117,60 @@ protected override Func<IBulkPagesController> GetFactory()
...
+                }
+            }
+
+            return fullPath;
+        }
+
+        private static int GetPageLevel(string pageName)
+        {
+            return pageName
+                .Replace(" ", string.Empty)
```
Comment (bdukes) [inline Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/BulkPagesController.cs:169]: Should this use `TrimStart`?

File: Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/BulkPagesController.cs [hunk 2]
```diff
@@ -111,6 +117,60 @@ protected override Func<IBulkPagesController> GetFactory()
...
+            var pageDirectory = GetPageDirectory(pageIndex, pages);
+
+            for (var index = 0; index < pageIndex; index++)
+            {
+                var loopedDirectory = GetPageDirectory(index, pages);
+                if (loopedDirectory != pageDirectory)
+                {
+                    continue;
+                }
+                else if (pageName == pages[index])
```
Comment (bdukes) [inline Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/BulkPagesController.cs:138]: This should probably be a case-insensitive check

**Review by bdukes — APPROVED** [review]
Looks reasonable to me

File: Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/BulkPagesController.cs (hunk 1 above)
Comment (berkarslan-xo) [reply Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/BulkPagesController.cs:169]: I did it on purpose to cover the cases like "> >"(with space) instead of ">>"

File: Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/BulkPagesController.cs (hunk 2 above)
Comment (berkarslan-xo) [reply Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/BulkPagesController.cs]: Fixed.

**Review by mitchelsellers — APPROVED** [review]
