### PR TITLE
Fix #5994: Sorting (A-Z) members of roles in PersonaBar

### LINKED ISSUE #5994: [Bug]: Sorting (A-Z) members of roles
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We manage a very large DNN site with different role groups and roles. The members of a role are now shown interchangeably. It would be nice if these were shown alphbetic (A-Z).

### Steps to reproduce?

1. Log in as Administrator
2. Choose in the admin personabar for Roles
3. Select a role with a lot of members

### Current Behavior

Notes that the members of the group are not shown to be alphabetic.

### Expected Behavior

Notes that the members of the group must be shown alphabetic (A-Z).

### Relevant log output

_No response_

### Anything else?

_No response_

### Affected Versions

9.13.2 (latest release)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Mostafa-Moafi**
Fix #5994: Sorting (A-Z) members of roles in PersonaBar

### CODE REVIEW

File: Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/RolesController.cs [hunk 1]
```diff
@@ -246,11 +246,11 @@ public HttpResponseMessage GetRoleUsers(string keyword, int roleId, int pageInde
                         Localization.GetString("InvalidRequest", Components.Constants.LocalResourcesFile));
                 }
 
-                var users = RoleController.Instance.GetUserRoles(this.PortalId, Null.NullString, role.RoleName);
+                var users = RoleController.Instance.GetUserRoles(this.PortalId, Null.NullString, role.RoleName).OrderBy(x => x.FullName).ToList();
```
Comment (bdukes) [inline Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/RolesController.cs:249]: Can we move the `OrderBy` call to the beginning of line 260? This would allows us to only specify it once, and avoid creating another copy of the list.

**Review by bdukes — COMMENTED** [review]
Thanks!

File: Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/RolesController.cs (hunk 1 above)
Comment (Mostafa-Moafi) [reply Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/RolesController.cs]: yes of course, I fix it.

File: Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/RolesController.cs [hunk 2]
```diff
@@ -246,7 +246,7 @@ public HttpResponseMessage GetRoleUsers(string keyword, int roleId, int pageInde
                         Localization.GetString("InvalidRequest", Components.Constants.LocalResourcesFile));
                 }
 
-                var users = RoleController.Instance.GetUserRoles(this.PortalId, Null.NullString, role.RoleName);
+                var users = RoleController.Instance.GetUserRoles(this.PortalId, Null.NullString, role.RoleName).ToList();
```
Comment (bdukes) [inline Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/RolesController.cs:249]:
```suggestion
                var users = RoleController.Instance.GetUserRoles(this.PortalId, Null.NullString, role.RoleName);
```

**Review by bdukes — APPROVED** [review]

**Review by valadas — APPROVED** [review]
Looks good
